### ISSUE TITLE
Layers test performance when using an actual image ~20 FPS

### ISSUE THREAD

**Issue by fu-raz** [joshmarinacci/aminogfx-gl#10]
I've tried the layers.js test and I see the same performance on my pi as described in the file. When using 5 layers on 1080p I get 60 fps.

Unfortunately this is only when using a rect. If I use an actual 1920x1080 jpeg image, using 5 layers the frame rate drops to ~20 FPS. You can see my test 'layers-image.js' in my test repo (https://github.com/fu-raz/amino-performance-tests.git)

I'm rendering 5 of the same full hd images on top of each other. Obviously this is not a 'real-world' scenario. In a real case scenario I would make sure only the top layer gets rendered. Using the z-buffer or just common sense.

What's the bottleneck here? Is this just the max performance of the Raspberry? Or does it have to do with the file/filetype. Would caching the image help? Or are there other tricks I could try? Doesn't the Pi have 2 GPU cores? would it be possible to use the second core as an offscreen buffer? I'm just spitballing here.

**Comment by cbratschi** [comment]
There is quite a difference between a texture (image) and a colored rect. In both cases a shader program is called to get the color of each texel (pixel). In case of a solid color it is a very simple shader whereas using a texture is more expensive. OpenGL processes usually more than one texel per pixel on screen. Interpolation and multi-pass sampling need time. That is why you see the lower framerate. The GPU executes shaders in parallel to get high framerates.

The fewer layers and pixels you process the better. If your scene is too complex, i.e. < 60 fps, you have to optimize it.
