### ISSUE TITLE
 failed to add service - already in use if OpenGL driver installed

### ISSUE THREAD

**Issue by salmon-charles** [joshmarinacci/aminogfx-gl#11]
Hello,

I am trying to use aminogfx-gl on a Raspberry Pi Model B.
I have been able to npm install without problem (the code has been compiled with no error).
I can run the demos if I don't active the OpenGL driver.

Now, when I activate the driver
rapsi-conf -> Avdanced Options -> GL Driver  
    G1 GL (Full KMS) OpenGL desktop driver with full KMSMS           
    G2 GL (Fake KMS) OpenGL desktop driver with fake KMSMS       
    G3 Legacy        Original non-GL desktop driver    
And I choose G1 or G2, i get the following error:

pi@rastapi:~/workspace/aminogfx-gl$ node demos/circle.js
* failed to add service - already in use?

What does that mean ?
If I choose G3, it works; but does that mean that aminogfx, in this case, uses a software emulation ?

Thanks

**Comment by salmon-charles** [comment]
Look's like it is a problem with the Raspberry itself and the openGl driver.
I have tried
sudo rpi-update
and split memory 128, 256 with no success
Look's like I am not the only one having these problem.

**Comment by cbratschi** [comment]
You cannot use any x window OpenGL driver because aminogfx-gl directly accesses EGL/OpenGL. No driver is needed for aminogfx-gl. The driver blocks any other software from accessing OpenGL.

128 MB GPU memory is recommended.

**Comment by salmon-charles** [comment]
OK, thanks
