### ISSUE TITLE
Dependencies missing and compiling problems

### ISSUE THREAD

**Issue by marcelonovaes** [joshmarinacci/aminogfx-gl#14]
Hi,

I just found a problem trying to use this. it appears that there are more dependencies than the ones listed:

* g++-4.7 
* cmake
* libfreetype6-dev
* libraspberrypi-dev

It also seems that Raspbian Stretch renamed a few libraries:

in the file:
aminogfx-gl/binding.gyp

Change:
	-lGLESv2 \
	-lEGL \

to:
	-lbrcmGLESv2 \
	-lbrcmEGL \

**Comment by cbratschi** [comment]
For Stretch the build settings have to be manually changed. Unfortunately there is no way to support both Raspbian version with a single build file. The latest version is now available. A Stretch enabled build will follow with the next major update.

**Comment by marcelonovaes** [comment]
I can't tell you how exciting it is to know that there's a major update coming up.
As a designer (who codes a bit & likes to tinker) this is the missing piece to enable me to do projects with quality on the Pi.
