### ISSUE TITLE
Rpi3 Buster

### ISSUE THREAD

**Issue by benhornshaw** [joshmarinacci/aminogfx-gl#16]
Hi i am trying to get a setup working currently on a Pi3 but with the though to upgrade to a Pi4 soon.

Ive managed to make this compile using the following.
Buster Lite
Node v10.18.1
NPM v6.13.4
sudo apt-get install libegl1-mesa-dev libdrm-dev libgbm-dev libfreetype6-dev libjpeg-dev libavformat-dev libswscale-dev libavcodec-dev
Git Clone https://github.com/cbratschi/aminogfx-gl.git
cd into aminogfx-gl 
npm install

That works fine. it gives a High Vulnerability security error of package "sshpk"
But fixing that doesn't help.

I get an error of:

> node: ../src/rpi.cpp:93: virtual void AminoGfxRPi::setup(): Assertion `driDevice > 0' failed.
> Aborted

Line 91-93 of that file is:
```
driDevice = open("/dev/dri/card1", O_RDWR | O_CLOEXEC);

assert(driDevice > 0);
```

Any help would be greatly appreciated. Especially moving forward with any tips i may need to move this onto a Rpi4 taking full advantage of the speed.

Thanks you all for fantastic work developing this

Ben

**Comment by benhornshaw** [comment]
Update
After having changed line 91 from
/dev/dri/card1
to
/dev/dri/card0

As im running a RPi 3 not 4
I now get much further. But I get the following error:

> shader compilation error: 0:6(2): error: No precision specified in this scope for type `vec4'
> 
> type: fragment shader
> 
> #version 100
> 
> #ifdef EGL_GBM
>         precision highp float;
> #endif
>         uniform vec4 color;
> 
>void main() {
>         gl_FragColor = color;
> }
> 
> node: ../src/renderer.cpp:86: virtual void AminoRenderer::setup(): Assertion `res' failed.
> Aborted

Thanks

**Comment by cbratschi** [comment]
Hi Ben,

Please use the official NPM package on RPi 3. My repository contains an alpha version of the RPI 4 implementation and is only useful for debugging purposes right now. Lots of things are still undocumented on RPi 4. Currently we have no schedule to finalize the RPi 4 version. Supporting video playback and all other features is quite some work. Until this is finished we won't update the official NPM package.

**Comment by benhornshaw** [comment]
Hi
Thanks for your quick reply.
So I did try that first. Both by git cloning the original joshmarinacci repository and trying to build that and also by simply
npm install aminogfx-gl

Im going to try both again now with a fresh install but having just tried the npm route i get the following error during the node-pre-gyp build.

> node-pre-gyp WARN Pre-built binaries not found for aminogfx-gl@1.7.0 and node@10.18.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
> /bin/sh: 1: freetype-config: not found
> gyp: Call to 'freetype-config --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
> 

Thanks Again

**Comment by benhornshaw** [comment]
Hi

So just an update.

Ive managed to make this work by doing the following.
Im using Rpi3 with Buster Lite
sudo apt-get update && sudo apt-get upgrade
git clone https://github.com/joshmarinacci/aminogfx-gl.git
cd aminogfx-gl
nano binding.gyp

find uncomment the Stretch and Comment Jessie
```
# Jessie
#"-lGLESv2",
#"-lEGL",
# Stretch
"-lbrcmGLESv2",
"-lbrcmEGL", 
```

find each instance of freetype-config and replace it with pkg-config freetype2
Save and then
npm install
There are quite a few warnings but mine has compiled sucessfully

Thanks You cbratschi
I look forward to any updates you have for Rpi4
