### ISSUE TITLE
Transparent app

### ISSUE THREAD

**Issue by rvlaskamp** [joshmarinacci/aminogfx-gl#7]
How can I make the app background transparent. I tried with this.opacity(0) but on the RaspberryPI the app is not transparent. I want to show OMXPlayer behind it.

**Comment by cbratschi** [comment]
You don't need omxplayer. Videos can be played right away by aminogfx-gl.

Transparency support was removed because it was not working correctly with the antialiased fonts. Probably it will work with a modified opacity value in DispmanX:

```
    VC_DISPMANX_ALPHA_T dispman_alpha;

    //Notes: works but seeing issues with font shader which uses transparent pixels! The background is visible at the border pixels of the font!
    /*
    dispman_alpha.flags = DISPMANX_FLAGS_ALPHA_FROM_SOURCE;
    dispman_alpha.opacity = 255;
    dispman_alpha.mask = 0;
    */

    dispman_alpha.flags = DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS;
    dispman_alpha.opacity = 0xFF;
    dispman_alpha.mask = 0;
```

**Comment by rvlaskamp** [comment]
Ok. Thanks for your response.

Can I play every video format? I want to play IPTV channels. Stream is multicast UDP. And the streams are interlaced. Is it possible to deinterlace the video with the aminogfx-gl video player?

**Comment by cbratschi** [comment]
RTSP and UDP are supported. However, interlaced videos are not supported right now. We only use progressive videos in our use cases. So there are no plans to add this feature.

**Comment by rvlaskamp** [comment]
Ok thanks. I changed the DispmanX alpha and now it's working for me. So for IPTV i'm using OMXPlayer, for other use cases I can use your video component. Thanks !

**Comment by cbratschi** [comment]
Could you please post your code changes? Probably someone else finds it useful in future.

**Comment by rvlaskamp** [comment]
The DispmanX alpha settings I used are

`dispman_alpha.flags = DISPMANX_FLAGS_ALPHA_FROM_SOURCE;
    dispman_alpha.opacity = 255;
    dispman_alpha.mask = 0;`

That is commented out in your source code, but works for me. I see some transparency around the edges of text views, but it's acceptable for now.

**Comment by T94T** [comment]
For those who need detailed information on changing this.

1. Edit rpi.cpp
$nano node_modules/aminogfx-gl/src/rpi.cpp
2. Uncomment disabled code block like this
```
    VC_DISPMANX_ALPHA_T dispman_alpha;

    //Notes: works but seeing issues with font shader which uses transparent pixels! The background is visible at the border pixels of the font!
   
    dispman_alpha.flags = DISPMANX_FLAGS_ALPHA_FROM_SOURCE;
    dispman_alpha.opacity = 255;
    dispman_alpha.mask = 0;
    
    /*
    dispman_alpha.flags = DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS;
    dispman_alpha.opacity = 0xFF;
    dispman_alpha.mask = 0;
    */
```
3. Rebuild module
$rm -rf node_modules/aminogfx-gl/build
$npm rebuild
